# Generated by Django 3.2.11 on 2025-02-06 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=8)),
                ('mobile', models.CharField(max_length=10)),
                ('address', models.TextField()),
                ('reg_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
