# Generated by Django 3.2.11 on 2025-02-06 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sitters_category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='sitter_cat')),
            ],
        ),
    ]
